print("Input first number:")
x = int(input())
print("Input second number:")
y = int(input())
print("Input third number:")
z = int(input())
f = ((x ** 5 + 7) / (abs(-6) * y)) / (7 - z % y)
print(round(f, 3))
